### ISSUE TITLE
Items melt in Forge when switching between worlds

### ISSUE THREAD

**Issue by Janivire** [alcatrazEscapee/tinkers-forging#12]
when you place any number of ingots in a forge that don't melt, iron in this case, and you heat them up to the max 1500, then log out of your world and either switch worlds or close the game completely, when you return all the ingots will be gone.

Logs just in case it helps: https://pastebin.com/ekmLiPPn

**Comment by alcatrazEscapee** [comment]
From initial testing it seems like this is a tick timer related issue. I'll see what I can do
Edit: I think I fixed it. Let me know if this doesn't work
