### ISSUE TITLE
Heat Retention

### ISSUE THREAD

**Issue by Fortist** [alcatrazEscapee/tinkers-forging#13]
Whoops.

Anyway, can there a config or -something- to have ingots hold their heat for a bit longer?

**Comment by alcatrazEscapee** [comment]
There are three config options that already do that.
`General Temperature Modifier`: how fast items heat up + cool down
`Charcoal Forge Temperature Modifier`: how fast items heat up in a charcoal forge
`Brick Forge Temperature Modifier`: how fast items heat up in a brick forge
