### ISSUE TITLE
Add support for Charcoal Pit's Fire Starter item

### ISSUE THREAD

**Issue by SeriousCreeper** [alcatrazEscapee/tinkers-forging#14]
Heya, 

really loving this mod so far. I'm using it in combination with Charcoal Pit to get a pretty close to TFC experience. 

Charcoal Pit adds a fire starter item that lets you set things on fire and activate its bloomery. 
Would it be possible to get support for it so that it could set a charcoal forge on fire? Not sure if that would be on this mods side, or charcoal pits. 

Cheers,
SC

**Comment by SeriousCreeper** [comment]
Just to add to it, support for the fire bow from primal core would great as well!

**Comment by alcatrazEscapee** [comment]
Both added https://github.com/alcatrazEscapee/alcatraz-core/commit/1ee2bee082ab0ba88ff548dc2b3d09cd5d4e33c9
