### ISSUE TITLE
Casted ingot with TC don't stack

### ISSUE THREAD

**Issue by AttilaPapp** [alcatrazEscapee/tinkers-forging#16]
Thank you for making this mod it really makes TC interesting again.

My only issue is that if I want to use TC casting instead of the forges in your mod, the ingots do not stack. It makes it impossible to forge tool/armor parts that need more than 1-2 ingots.

I tried to use redstone to sync the casting with more smeltery drains and managed to get 2-3 ingots stack but that is not enough for the large plate or other bigger parts.

Am I missing something?

**Comment by alcatrazEscapee** [comment]
You can't merge stacks that have different temperatures. You aren't missing anything. Since they technically have different NBT the best I can do is add a crafting recipe to merge items with different heat into one stack

**Comment by AttilaPapp** [comment]
I don't know  how of a job it would be to provide ingot casts for bigger amounts. 2 ingot worth for tool heads, 8 for plates and so on. Or even easier to just make the casted blocks from TC to have the tempereture as the ingots have and when you craft ingots from the block they would inherit the temperature from the block.

**Comment by AttilaPapp** [comment]
Alternatively, it would be great to have a config option to turn on/off the automatic temp NBT on tinkers casting. This way one can just cast a block of iron craft it quickly to ingots and reheat it to reach working temperature.

Right now the added temp on casting defeats the point of tinkers integration because one can not cast enough ingot with the same temperature to make more expensive tool heads and parts.

**Comment by alcatrazEscapee** [comment]
I've added the config option you suggested. Should be in 1.1.0. I will look at how to fix this better tho, just probably won't happen soon.

**Comment by AttilaPapp** [comment]
Thank you very much!

Looking forward to seeing where you are going to take this mod. So much potential...
