### ISSUE TITLE
Make the anvil remember the last operation

### ISSUE THREAD

**Issue by LeoBeliik** [alcatrazEscapee/tinkers-forging#19]
When I try to make multiple batches of the same item, the anvil constantly reset the item to make.
For example, if I wanna make 5 pickaxe heads, everytime that I make one, the anvil goes to the hammer recipe, and I need to change to the pickaxe head again.

**Comment by alcatrazEscapee** [comment]
Memory of which pattern is based on the item, so if you work an item and remove it, it will remember the recipe and you'll only have to select it once per item. That takes precedence over remembering the last thing that was done.
