### ISSUE TITLE
[Feature Request] No Tree Punching metal tool part forging

### ISSUE THREAD

**Issue by WrongWeekend** [alcatrazEscapee/tinkers-forging#2]
From what I understand this mod replaces the metalworking that was removed from No Tree Punching. While I like Tinkers Forging's mechanics I think that it would be a good idea to have the same process for creating the NTP tools, including the knife, saw, and mattock.

**Comment by alcatrazEscapee** [comment]
Tool parts for No Tree Punching tools should be added in 1.0.3, along with the relevant crafting and anvil recipes.
