### ISSUE TITLE
takes too long to create the world

### ISSUE THREAD

**Issue by luoxingzlx** [alcatrazEscapee/tinkers-forging#21]
This problem occurred in version 1.1.0 and above, using my modpack (about 250 mods), when I don't add tinkersforging or use version 1.0.7, it takes about 1min30s to 2min30s to create and enter a new world.(Although I have used RoguelikeDungeons which will load new chunks), when I used version 1.1.0/1.1.1/1.1.2, this time was extended to more than 5min.I don't quite understand why In this way, I can only provide you with the log, this is the log when I add the tinkersforging1.1.2 version.

forge 14.23.5.2825
[latest.log](https://github.com/alcatrazEscapee/tinkers-forging/files/3058339/latest.log)

**Comment by luoxingzlx** [comment]
I also tried other modpack, such as [this](https://minecraft.curseforge.com/projects/dungeons-dragons-and-space-shuttles), creating world time extended from 2m30s to 6m35s.But adding this to Enigmatica 2: Expert hasn't changed much.

**Comment by alcatrazEscapee** [comment]
Tinker's Forging adds no world gen, and nothing that should impact creating a world in any way. I have not been able to notice any adverse effects. I'm assuming there's some weird interaction between the ~250 mods, but I am not going to try and track that down. If you have more information or a specific reason, I can take a look. Until such time I am closing this.
