### ISSUE TITLE
Problem with sponge?

### ISSUE THREAD

**Issue by Aphrodite2430** [alcatrazEscapee/tinkers-forging#22]
i notice this message on the server console when i interact in any way with the brick furnace, i don't know if this is a problem of the mod or if it's sponge fault 

`[Server] Server thread/INFO [Sponge]: Container was not captured. No ClickInventoryEvent will be fired! Container: class com.alcatrazescapee.tinkersforging.common.container.ContainerForge PacketState: SecondaryInventoryClickState`

i don't know if the following is a direct consequences of this problem but even if the ingot is at max temp i can't work it in the anvil

**Comment by alcatrazEscapee** [comment]
Sponge breaks a lot of mods - I will not support it, sorry. Either remove sponge or remove Tinker's Forging.
