### ISSUE TITLE
[Feature Request] Base Metals suite support

### ISSUE THREAD

**Issue by Dragnier** [alcatrazEscapee/tinkers-forging#23]
I would love to see built in support for Base Metals tools and armor. Going further and including tools and armor from the rest of their mods like Modern Metals and such would be even better.

**Comment by JadianRadiator** [comment]
This issue needs to be closed, as it has been fixed.
In older versions,
Tinker's Forging (presumably) hard-coded support _directly_ to the items, and _**not**_ with Tinkers Construct's api.
Which had caused it to only support vanilla Tinker's Construct, and not any addons.
Newer versions (presumably) instead integrate via Tinker's Construct's api.
Which more or less then gives Tinker's Forging integration with any/all Tinker's Construct addons' stuff in an addon.
