### ISSUE TITLE
Count Support for Anvil CraftTweaker Support

### ISSUE THREAD

**Issue by Loriborn** [alcatrazEscapee/tinkers-forging#25]
Vanilla Tinkers Forging recipes require specific amounts of ingots in order to create a component, but trying to use NBT tags (ex. <minecraft:iron_ingot>.withTag({Item: {Count: 2}})   ) doesn't actually work and thus there's no way to make certain recipes more expensive than others, unless there's something I'm missing. IIngredient methods, like <item>.amount(x) also do not work.

**Comment by alcatrazEscapee** [comment]
An ItemStack doesn't use NBT to specify amount. To specify an amount you can use `*` (multiplication):
```
import mods.TinkersForging.Anvil;
Anvil.addRecipe(<minecraft:iron_ingot> * 3, <minecraft:iron_bars> * 8, 2, "hit_last", "hit_second_last");
```
Which will produce the result:
![example_recipe](https://user-images.githubusercontent.com/35673674/58373530-8aae1180-7efd-11e9-9c6a-36cab4987ddb.PNG)
