### ISSUE TITLE
Forging minigame unforgiving.

### ISSUE THREAD

**Issue by Octopork** [alcatrazEscapee/tinkers-forging#3]
Current implementation of the forging mini game can be a quite unforgiving when it comes to hitting the target indicator. I've had a couple of cases in testing where i may end up only a few pixels off, coupled with having to reheat the metal constantly the game gets tedious very quickly.

A possible solution could be to make this a target range rather than value. While a global option would be easiest to implement a per material setting could add some more depth by making early game materials like copper and bronze easy to work with and higher tier materials much harder to forge.

**Comment by alcatrazEscapee** [comment]
I've added two config options - one for a global range and one for a per-tier range. Per-metal range seems too specific, and since you can already configure the tiers of all the metals that can be forged, that should be sufficient.
