### ISSUE TITLE
Thermal foundation materials not detected

### ISSUE THREAD

**Issue by Dir7y** [alcatrazEscapee/tinkers-forging#31]
almost all materials register, except platinum, signalum, enderium, and lumium
recipes for the heads show up, but they have no ingots as a valid input
side question: is there documentation anywhere on adding materials manually through the configuration file? can’t seem to get it to work, tried modid:item:meta, modid:item@meta, and modid:item;meta, but none seem to work
latest mod builds

**Comment by alcatrazEscapee** [comment]
If you are using the `forceEnabledMetals` config option, it expects a material name as registered with Tinker's Construct. (Not an item registry name) It doesn't do anything except force Tinker's Forging to enable the material provided that it already exists and is registered with TiCon.

As for the other concern, it'd help to know exactly where the problem is. Can you see items made from those materials? Is the recipe empty in JEI because there are no valid inputs (i.e. no `ingotPlatinum`?) Are the items added but the recipe invisible?

**Comment by Dir7y** [comment]
ah, that explains why nothing I did effected anything
all the material tool/armor components show up, along with jei recipes, but the ingots to create the items do not show up
for example, working recipe has two ingots to one pickaxe head, but the non functioning recipes have a pickaxe head and leave the ingot slot empty
I’ll take a screenshot when I get off work
It’s strange though, the basic materials like copper, tin, etc work, even with thermal variants, all except the uniques that are added by thermal

**Comment by alcatrazEscapee** [comment]
Is the input empty? Or is it an empty ore dict? (Those are two different things)
 - If you are viewing in JEI, it will show no input if the input is an ore dict name (for example, `ingotPlatinum`), and there are no valid items for that name.
 - Can you make the items with no input? (that would be the case if the input is empty, you shouldn't be able to if it's an empty ore dict.)

Basically, Tinker's Forging will create recipes that accept `ingot[Material]` as the input. Make sure that the relevant ingots have those ore dictionary names. (There's a config option in AlcatrazCore that will allow you to see ore dictionary names as part of the item tooltip, if they are missing try adding them via craft tweaker, that should solve the issue if I'm understanding correctly)

**Comment by Dir7y** [comment]
inputs empty, ingots that would normally be used are not able to be placed in the furnace
I’ll try removing the ordict and setting it again in a script

**Comment by Dir7y** [comment]
oredicts are applied by default, but checked out other materials part recipes, some just dont even register, while others do, just without input items
tried putting it in a forge, doesnt allow being placed in the slots
![lumium hammer head](https://user-images.githubusercontent.com/54538598/63732966-74309280-c82b-11e9-8148-75bb9a8b5114.png)
![no lumium pickaxe head](https://user-images.githubusercontent.com/54538598/63732967-74309280-c82b-11e9-87e1-06ec3409fb89.png)
gonna force material heat in my script and see if that lets it register

**Comment by alcatrazEscapee** [comment]
If it's not getting picked up by the furnace, that means it is missing the heat capability, which again indicates that the ore dictionary name is not present. Have you verified that `ingot[Material]` exists, and it is using the same material name as the material registered with Tinker's Construct?

It may also be a problem of which mods load first.

**Comment by Dir7y** [comment]
they all have valid oredicts, and adding heating didn't do anything other than allow the ingot to be heated
I'll try loading tinkers before

**Comment by Dir7y** [comment]
realized in order to change load order I would have to download the source, change the name to ztinkersforging, and compile, correct?

**Comment by alcatrazEscapee** [comment]
Add "after:thermalfoundation;" to the end of https://github.com/alcatrazEscapee/tinkers-forging/blob/94a1f0d5d29beb578b63e76545da35aa973ea7e0/src/main/java/com/alcatrazescapee/tinkersforging/TinkersForging.java#L53

**Comment by Dir7y** [comment]
source isn't buildable, keep getting this error when building both the modified and unmodified versions
![compilation error](https://user-images.githubusercontent.com/54538598/63819112-e8853780-c8f8-11e9-8172-f29c8b6e03f7.png)

**Comment by alcatrazEscapee** [comment]
Just remove the jar signing task

**Comment by Dir7y** [comment]
said it was missing other files so I added the core src too, but that doesnt fix much
tried gradlew build --continue and gradlew assemble, but they dont skip the errors
do I gotta add all possible mods or am I missing something?
also noticed ingame that missing recipes wasnt just restricted to the mentioned materials, but pickaxe heads as a whole
![compilation error](https://user-images.githubusercontent.com/54538598/63902388-32842100-c9be-11e9-9d6a-5c2ab1343876.png)

**Comment by alcatrazEscapee** [comment]
Ugh, this is where I learn my dependency management is crap and undocumented. Adventurers Toolbox and Guide API I think I both have in `./libs` instead of importing via gradle

**Comment by Dir7y** [comment]
new set of errors, this time from thaum
![new errors](https://user-images.githubusercontent.com/54538598/63903467-69f4cc80-c9c2-11e9-9108-032ebdcc471c.png)

**Comment by alcatrazEscapee** [comment]
Nothing I've ever seen before

**Comment by Dir7y** [comment]
nothing I’ve been trying has worked, I don’t think I can compile this
could you clean up dependencies sometime, so others can alter the mod?

**Comment by alcatrazEscapee** [comment]
Doubtful - all my time recently has been taken up with either TFC development or porting stuff to 1.14. I'm not eager to get back into development for Tinker's Forging short of a 1.14 port, which will likely involve ripping those dependencies out anyway.

**Comment by Dir7y** [comment]
thanks for the info then, I’ll try removing toolbox compat
