### ISSUE TITLE
override?

### ISSUE THREAD

**Issue by UnlimitedTurtlez** [alcatrazEscapee/tinkers-forging#32]
players still use the original tinker methods and ignore this mod completely, why is it broken?

**Comment by alcatrazEscapee** [comment]
Because this mod does nothing to override tinker's casting recipes by itself. If you want that, you need to configure tinker's construct, either making the smeltery inaccessible or removing the recipes yourself.

**Comment by UnlimitedTurtlez** [comment]
so i need to remove the smeltry? the issue was i had no idea what to limit
