### ISSUE TITLE
Is nothing supposed to be disabled?

### ISSUE THREAD

**Issue by BlueYoshi68** [alcatrazEscapee/tinkers-forging#37]
Every other part of tinkers construct is still enabled...like..default forging. It makes the anvil useless. How do I fix this? I want to use this mod instead of the normal forging so bad.

**Comment by alcatrazEscapee** [comment]
Yes, I'm not disabling parts of Tinker's. That's left up to the packmaker how they want to go about that.

**Comment by BlueYoshi68** [comment]
That's a really dumb excuse. You basically just said, "Im letting it be up to mod pack makers how they want to get my mod to work in a meaningful way." That's kind of your job but ok.
