### ISSUE TITLE
Question-what is the block Id for the charcoal forge?

### ISSUE THREAD

**Issue by Garnin** [alcatrazEscapee/tinkers-forging#39]
I want to use the block as a heat source in some other mods but waila just shows minecraft:charcoal.

**Comment by Janivire** [comment]
Oooh i can answer this one!

"tinkersforging:charcoal_pile" > Unlit pile

"tinkersforging:charcoal_forge" > Lit pile

They also use a meta for how full it is, 1-7 for unlit, 8-14 on the lit. in case you only want a full forge to be used. Hope this helps as it was a pain to get. needed it for my own scripts to try and fix a cross mod issue.

**Comment by alcatrazEscapee** [comment]
Also F3 will tell you what block you are looking at...
