### ISSUE TITLE
Ingots on server are instantly Brilliant White.

### ISSUE THREAD

**Issue by ejektaflex** [alcatrazEscapee/tinkers-forging#4]
Trying to use Tinkers' Forging on a multiplayer server, but it seems not to display values correctly. When putting an iron ingot into the Brick Forge, for example, the item flickers constantly as if it was continually entering and leaving the Brick Forge inventory. It also displays it's heat as "Brilliant White", despite not having been touched.

All seared bricks that get poured out of a smeltery have this same problem, and therefore cannot be stacked.

Despite these ingots being seemingly very hot, attempting to pound them into shape on the anvil still says "This item is not hot enough to work!", leading me to think that this is just a visual error (Though the flickering is still unexplainable)

Switching to advanced mode shows the true temperature:

![Photo Here](https://i.imgur.com/IzEHHCD.png)

Here, in the charcoal pit, the item does slowly increase in temperature. In the brick forge, it rapidly increases in temperature every time it flickers.

AlcatrazCore 1.0.3
Tinkers' Forging 1.0.1
Tinkers' Construct 1.12.2-2.11.0.106
Forge 14.23.5.2796
Multiplayer server.

**Comment by alcatrazEscapee** [comment]
Should be fixed in 1.0.3
