### ISSUE TITLE
Other mod Weapons/tools

### ISSUE THREAD

**Issue by Ceifeire** [alcatrazEscapee/tinkers-forging#42]
Hey i was wondering if there was a way to add other weapons and tools to the forge. The big one that I am looking at doing this with is Spartan Weapons. It would be cool to be able to add those tools or some of them depending on which ones to the forge.

**Comment by alcatrazEscapee** [comment]
Yes
<https://github.com/alcatrazEscapee/tinkers-forging/wiki/Craft-Tweaker-Integration>
