### ISSUE TITLE
Anvil Tier Changes

### ISSUE THREAD

**Issue by Ceifeire** [alcatrazEscapee/tinkers-forging#48]
Hey would it possible to change an anvils given tier? I am currently making a modpack with a massively overhauled tool/gathering system and just learned that even after turning off respecting tiers the anvil still respects material tiers.

**Comment by alcatrazEscapee** [comment]
No.

**Comment by Ceifeire** [comment]
Thanks for the answer. Any idea why almost all of my anvils are tier 5 though instead of distributed around 1-5
