### ISSUE TITLE
do temperture change items nbt data?

### ISSUE THREAD

**Issue by dobbyjang0** [alcatrazEscapee/tinkers-forging#49]
how can I check it?

**Comment by dobbyjang0** [comment]
How does this mod's temperature system work?

**Comment by alcatrazEscapee** [comment]
It uses a capability, and stores the temperature only on last update tick. When you view the tooltip, it only visually shows what the temperature *would be* - the item is still recorded as having whatever temperature it was on the last time it was updated. Tinker's Forging tracks ticks internally to do this interpolation.

TL;DR
No they do not change item NBT
You check it via the tooltip
It's complicated.
