### ISSUE TITLE
Pig Iron tooltip displays melting temperature but calls it working temperature.

### ISSUE THREAD

**Issue by ejektaflex** [alcatrazEscapee/tinkers-forging#5]
I put images here:

https://imgur.com/a/Z5MZNaY

Basically, the book states that Pig Iron has a working temp of 250C and a melting temp of 400C, but the tooltip when you heat Pig Iron states that it has a 400C working temp. If one doesn't check the book, their ingot is going to accidentally just melt when they think it's at working temperature. This  may be true for some other ingots, but I haven't checked.

Also, as you can see, taking the ingot sometimes leaves a "ghost ingot" inside the brick forge. Clicking on the ghost ingot deletes it, though.

I do love the mod, though! Keep it up.

**Comment by alcatrazEscapee** [comment]
That was an oversight when moving around some temperatures, thanks for spotting it. (Pig iron will actually melt at 250 right now - oops)
The ghost ingots are a side effect of the fact that the temperature is getting updated every tick - nothing I can really do about that.

Should be fixed in 1.0.4
