### ISSUE TITLE
Tinker's Forging is currently unplayable

### ISSUE THREAD

**Issue by JadianRadiator** [alcatrazEscapee/tinkers-forging#55]
Ingots out of the brick forge aren't staying workable long enough to actually forge them.
[Exported CurseForge MC profile](https://drive.google.com/file/d/1t5ujQhOuDJV4oFFvTwfPmTq5T_rwtQP2/view?usp=sharing).

**Comment by alcatrazEscapee** [comment]
Ya know what you could do? Put them back in the brick forge to heat them up again! They'll keep their progress. ;)

**Comment by JadianRadiator** [comment]
so I have to heat them back up after every 2 or 3 clicks of the forging buttons?
