### ISSUE TITLE
NoUpdates - but a wish to continue

### ISSUE THREAD

**Issue by Xarmat-GitHub** [alcatrazEscapee/tinkers-forging#58]
Hello Alcatraz, I read this on your Modpage:
"**This mod has been discontinued. It will not be receiving updates or support!**"

And I want to ask you, if you may change your mind and could solve these Tickets:

**Must Have:**
- [Suggestion] CraftTweaker | removeItemHeat #50
-- Because I can not change the heat on iron, this get hard for me to workaround

**Should Have:**
- [Suggestion] Disable Heat #47
-- Allowing the Anvil to function without heat, would make things easier for the future playerbase

So I would love to use your mod in my modpack as a key element for advanced crafting with artisan worktables.
But I need an option to change the heat from iron at least :/

Would love to hear from you, and thanks for the effort. 

_________________________________________________

Nice to have:
- [Suggestion] Turn off Puzzle Bar #46
-- This is optional, and I think I can life with it
- [Suggestion] Intuitive HUD reading #45
-- This may be nice for some players that can not trick there mind, so optional too
- [Suggestion][CraftTweaker] Durability for Tools #44
-- I am working with Artisan Worktables, maybe I can hack this in some way with Craft Tweaker

**Comment by alcatrazEscapee** [comment]
No. Shocking, I know - I meant what I wrote.
